version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23042024Ma
      POSTGRES_DB: api_alunos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:23042024Ma@db:5432/api_alunos?schema=public
    depends_on:
      - db

volumes:
  postgres_data:
